apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: us-south1-docker.pkg.dev/micro-chiller-458819-r4/oreo-repository/orchestrator:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: orchestrator-config